arrowFront = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Arrow_Front.png"
arrowLeft = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Arrow_Left.png"
arrowRight = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Arrow_Right.png"
arrowBack = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Arrow_Back.png"
arrowReturn = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Arrow_Return.png"
Brigitte = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Brigitte.png"
Ulrich = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Ulrich.png"
Miriam = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Miriam.png"
Gottfried = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Gottfried.png"
Ebene = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Ebene.png"
Ufer = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Ufer.png"
Wald = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Wald.png"
Hoehle = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Hoehle.png"
Veridia = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Veridia.png"
Morast = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Morast.png"
Karte = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Karte.png"
KarteButton = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Map_Button.png"
Vorluna_Bild= "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\Hoehle_Vorlunda.png"
WorldMap = "C:\\GitHub\\Schatten_ueber_Veridia\\Bilder\\WorldMap.png"



