Intro_1 = "You are an intrepid adventurer hailing from a distant land, drawn by curiosity to these uncharted territories. \nAs your boots touch the unfamiliar soil, an unsettling sensation sends shivers down your spine, an ominous weight \nlingering in the air. With every step, an eerie presence lurks, a feeling of being perpetually watched, as you step \ninto a realm where things seem awry."
Intro_2 = "The land lies in a disquieting stillness, an eerie hush that chills the very core of your being. The path you \ntraverse remains devoid of any sign of life, as if the land has swallowed its inhabitants in an unsettling silence. \nNature, too, behaves in an oddly tranquil manner, with the breeze barely whispering through the trees and even \nthe leaves underfoot seeming reluctant to rustle." 
Intro_3 = "It's a disconcerting calm, as if the very essence of existence holds its breath, leaving you alone with your thoughts \nand the oppressive weight of the unknown."
Intro_4 = "Before you stands a small village, its once-charming exterior now smothered by the surrounding stillness. An old, \nweathered wayfarer's sign points the way to a place named 'Veridia'. As you step further into the village, it becomes \nevident that you are entering what appears to be the village's marketplace. The eerie silence continues to press \ndown on the scenery, creating a sense of desolation that clings to every building and structure."

Boss_1 = "As you stand victorious over the defeated, gruesome beast, a profound sense of dread takes hold. The monster's \nsoul, now severed from its monstrous body, drifts ominously away. Its spectral essence moves with an eerie \nswiftness, heading inexorably toward the village of Veridia."
Boss_2 = "A shiver runs down your spine, for it becomes clear that the malevolent force, once confined within the creature, \nis now unleashed upon the unsuspecting village, and it falls to you to confront this new, otherworldly threat."
Boss_3 = "You run as fast as you can back to the village, only to find it in ruins. The souls of the monsters you've defeated \nnow haunt the village, causing chaos and destruction."
Boss_4 = "Ultimately, these restless souls converge at the marketplace, merging together to form a colossal monstrosity. \nThe once-peaceful village of Veridia has turned into a nightmare, and the fate of the land hangs in the balance."

Brigitte_1 = "Well, hello there, stranger. I'm Brigitte. You find yourself in the quiet village of Veridia.What can I do for you?"
Brigitte_2 = "You want to know more about this place? Well, it's not what it used to be, that's for sure. These last few months, \nthings have taken a dark turn. "
Brigitte_3 = "Unsettling occurrences, like people vanishing without a trace, strange sounds echoing in the night, and those \nmysterious lights that draw the curious into the unknown. Many who wander towards those lights are never \nseen again."
Brigitte_4 = " It's said that these lights dance over the water or between the woods, far off in the distance, luring those who seek \nanswers into the heart of darkness. \nSome say it's the work of spirits or otherworldly forces, but no one knows for sure."
Brigitte_5 = "I have never seen them myself but I've heard the stories, and it's enough to send shivers down your spine. \nI've seen good people disappear, and it's as if the village itself is holding onto secrets that it refuses to share."
Brigitte_6 = "Veridia needs all the help it can get in these troubled times. \nBe careful, though, for there's something dark and ancient that stirs in the heart of this misty village."

Ulrich_1 = "..."
Ulrich_2 = "... Ah, I didnae see ye there. Whit dae ye be wantin'?"
Ulrich_3 = "Ye want tae ken mair 'boot this place? But why? This place be cursed, I tell ye."
Ulrich_4 = "For the past few months, I've seen lights on the horizon. They're... allurin', like they're callin' oot tae me, promisin' \na peaceful embrace. But dinnae be fooled. I fled from them wi' all the strength I could muster. I dare nae return tae \nthe coast."
Ulrich_5 = "They're nae just any lights, I tell ye. They're enchantin', like sirens singin' their songs. They beckon ye intae the \ndepths o' the sea. Many a fisherman ventured too close, drawn by the beauty o' the lights, and they vanished \nwi'out a trace."
Ulrich_6 = "Some say a monstrous beast lurks beneath those waters, a creature o' nightmares. They say it's been spotted, \nsomethin' colossal, wi' eyes that gleam like forgotten secrets."
Ulrich_7 = "I saw its shadow one night, and I've nae ventured tae the coast since."
Ulrich_8 = "Only a fool would dare tae enter this cursed place. The coast has become a treacherous place, and it hungers for \nthe unsuspectin'. But dae whit ye will."
Ulrich_9 = "I cannae stop ye anyway."

Gottfried_1 = "Ah, greetings, traveler! I'm Gottfried, a merchant of rare wares and curious treasures."
Gottfried_2 = "Let me tell you of something extraordinary. I was exploring the swamp, see, for hidden gems and rare finds, \nwhen I suddenly felt like I was being watched."
Gottfried_3 = "But it gets even stranger. As I ventured deeper between the gnarled trees and murky waters, I saw them. Lights, \nnot like any I've seen before, began to appear, surrounding me, as if they were listening to my every breath."
Gottfried_4 = "They were like fireflies, but brighter and more mesmerizing. They danced between the trees, and their glow seemed \nto pierce the darkness of the swamp. I was entranced, but then... a wave of panic washed over me."
Gottfried_5 = " Suddenly, the lights closed in, and I felt a presence, as if I had stumbled upon something beyond my \nunderstanding. Fear gripped me, and I fled as fast as my legs could carry me, back to the safety of the village."
Gottfried_6 = "If you do find answers, I'm sure there'll be a reward in it for you. But be cautious; the swamp hides many secrets, \nsome best left undisturbed."

Miriam_1 = "Oh, hello there. I'm Miriam. You wouldn't believe what I saw last night."
Miriam_2 = "I saw lights rising from the well, and they... they flew towards the forest. They looked so friendly, I wanted to \nfollow them, but I was too scared to leave the house in the dark."
Miriam_3 = "They were like tiny stars, but they moved on their own. Not like any stars I've seen before. They danced and \ntwinkled, and I felt like they were calling me."
Miriam_4 = "They went towards the forest, disappearing into the trees. I wish I could have followed them to see where they \nlead, but the night is so dark, and the stories about the woods are frightening."
Miriam_5 = "If you find them, please tell them I'm not afraid. I just want to know where they came from and why they \nvisited me."

Wald_1 = "You stand before a dense thicket of gnarled, moss-covered trees. The murmur of a hidden stream trickles softly \nto your ears."
Wald_2 = "There is a constant rustling in the underbrush, a presence you can't quite see. It feels as though you're being closely \nwatched, with every step met by the eerie sound of leaves crunching underfoot, accompanied by an occasional \nlow growl"
Wald_3 = "The trees grow denser, and the forest appears even more impenetrable. A spooky wind rustles through the air."
Wald_4 = "Amongst the trees, you see decayed tree stumps and overgrown stones. An eerie silence hangs in the air."
Wald_5 = "The heart of the forest opens before you. An abandoned, decaying house stands in the midst of a small clearing, \nits windows shimmering in the darkness."
Wald_6 = "You hear the rustling of animal paws in the underbrush, but you can't discern the source. Tension fills the air."
Wald_7 = "Here, the path disappears into impenetrable thickets. You hear eerie sounds in the distance."
Wald_8 = "The ground is covered with damp moss that squeaks beneath your feet. A chilling mist drifts through the treetops."
Wald_9 = "A faint whisper reaches your ears, and you feel as if you're being watched. In the distance, you spot a sinister \nshadow amidst the trees."
Wald_1_Examine = "The thicket of trees seems ancient and overgrown, their bark rough to the touch. Moss and lichen cling to the \ntrunks, shrouding them in eerie shades of green and gray."
Wald_1_Touch = "As you run your fingers along the tree bark, a dampness clings to your skin, and you can feel the rough, knotted \ntextures of the trees."
Wald_1_Perceive = "You pause, and your senses sharpen. The forest is alive with the rustling of leaves, and you detect faint \nechoes of distant whispers."
Wald_1_PickUp = "You search for something to pick up, but in this tangled mess of trees and underbrush, there's nothing of \ninterest to be found."
Wald_2_Examine = "As you closely examine the surroundings, you notice the foliage has been disturbed, and there are fresh paw prints, \nsuggesting a large creature nearby."
Wald_2_Touch = "You reach out cautiously to touch the nearby tree bark, feeling its rough texture. It sends a shiver down your spine, \nmaking you acutely aware of the wild presence lurking around."
Wald_2_Perceive = "Your senses are on high alert. The forest's subtle sounds intensify, and you discern the faint, steady breathing of a \nhidden entity, amplifying the sense of being observed."
Wald_2_PickUp = "You contemplate the idea of picking up a nearby stick or stone for protection, recognizing that the threat could be \nvery close."
Wald_3_Examine = "The trees here seem to press in on you from all sides, creating a feeling of claustrophobia. The air is thick with \nan unsettling silence."
Wald_3_Touch = "The trees' bark feels damp and eerie to the touch, like a cold, clammy embrace."
Wald_3_Perceive = "You take a deep breath and listen intently, but all you hear is the eerie wind sighing \nthrough the branches."
Wald_3_PickUp = "There's nothing of interest to pick up in this part of the forest."
Wald_4_Examine = "Amongst the undergrowth, you spot decaying tree stumps and overgrown stones, remnants of an ancient presence \nin the woods."
Wald_4_Touch = "The tree stumps are rough and crumble beneath your touch, while the stones are slick with dampness."
Wald_4_Perceive = "The eerie silence is punctuated by distant, unidentifiable sounds. It's as if the forest \nholds its breath."
Wald_4_PickUp = "There's nothing here that warrants being picked up."
Wald_5_Examine = "The abandoned house stands in desolation, its windows reflecting the pale moonlight. The structure looks \nweathered and broken, a story untold."
Wald_5_Touch = "Your hand brushes against the decaying wood of the house, a chilling reminder of past \ninhabitants."
Wald_5_Perceive = "You can hear the faint creaking of the old house, as if it's whispering secrets of the past. \nThe silence in the clearing seems pregnant with tension."
Wald_5_PickUp = "There's nothing here to pick up, except for the heavy sense of foreboding."
Wald_6_Examine = "The underbrush hides elusive creatures, their presence felt but not seen. Unseen eyes seem to watch your \nevery move."
Wald_6_Touch = "You reach out to touch the underbrush, but it quickly slips through your fingers, \nleaving you with an eerie sensation."
Wald_6_Perceive = "As you focus your senses, you hear the rustling and scampering of small animals, \nthough they remain hidden in the foliage."
Wald_6_PickUp = "The underbrush yields nothing worth picking up, only a sense of unseen life."
Wald_7_Examine = "The path vanishes into an impenetrable thicket. The tangled mass of branches and \nunderbrush blocks your view."
Wald_7_Touch = "Your hand brushes against the thick underbrush, and it feels like an impenetrable wall."
Wald_7_Perceive = "As you stand before the thicket, you hear strange sounds emanating from its depths, a cacophony \nof whispers and rustling leaves."
Wald_7_PickUp = "There's nothing here to pick up, only the unsettling mystery of what lies beyond."
Wald_8_Examine = "The damp moss beneath your feet feels like a soggy carpet. It clings to your shoes and \ndampens your steps."
Wald_8_Touch = "The moss is cold and slimy to the touch, almost like the grasp of unseen fingers."
Wald_8_Perceive = "The mist drifts through the forest, obscuring your vision and making you hyper-aware of every sound. \nThe air is thick with foreboding."
Wald_8_PickUp = "The mossy ground offers nothing to pick up at the moment."
Wald_9_Examine = "The sinister shadow deep within the trees remains elusive, and you can't make out \nany details from here."
Wald_9_Touch = "Your hand reaches out, but it only encounters the cool, empty air. The shadow remains distant and enigmatic."
Wald_9_Perceive = "The whispering grows more pronounced, and you sense that you are not alone. An eerie presence lurks nearby, \njust beyond your perception."
Wald_9_PickUp = "In this part of the forest, there's nothing to be picked up, only a growing sense of unease."

Hoehle_1 = "You stand at the entrance of a dark cave, where darkness reigns and an oppressive silence prevails."
Hoehle_2 = "A long, narrow corridor stretches before you, its walls adorned with eerie, shimmering patterns."
Hoehle_3 = "The floor is covered in glowing mushrooms that flood the cave's interior with an eerie, greenish light."
Hoehle_4 = "You find yourself at a location where a deep, ominous rumbling emanates from the depths of the cave."
Hoehle_5 = "You enter a secret chamber in the cave, surrounded by ancient relics and mysterious runes."
Hoehle_6 = "The cave splits at this point into a dark fork, leading into the unknown."
Hoehle_7 = "Above you, massive stalactites hang like menacing spears from the cave's ceiling while water drips and trickles."
Hoehle_8 = "An ominous darkness and a sinister presence pervade this part of the cave."
Hoehle_9 = "Boss"
Hoehle_1_Examine = "Before you stretches a gloomy cave entrance, surrounded by a shadowy, oppressive feeling. Moss and lichen \ncover the cold, stony walls."
Hoehle_1_Touch = "The cave walls are ice-cold and feel damp. Your hand glides over the rough, uneven rock."
Hoehle_1_Perceive = "A faint, eerie whisper echoes from deep within the cave. You hear the echo of your own footsteps in the darkness."
Hoehle_1_PickUp = "There's nothing nearby to pick up."
Hoehle_2_Examine = "You find yourself in a shadowy corridor with walls adorned with bizarre, shimmering patterns. The darkness here \nseems particularly impenetrable."
Hoehle_2_Touch = "The patterns on the walls are cold and smooth. Your touch reveals no secrets, only a frosty chill."
Hoehle_2_Perceive = "In this corridor, it's so quiet that you hear the rushing of your own blood in your ears. The patterns on the walls \nseem to move ever so slightly."
Hoehle_2_PickUp = "There's nothing to pick up here."
Hoehle_3_Examine = "The floor is covered with glowing mushrooms, casting a spooky, greenish light in the cave. The air smells of decay \nand must."
Hoehle_3_Touch = "The mushrooms are soft and rubbery, and your finger leaves imprints in their pale glow."
Hoehle_3_Perceive = "The greenish light of the mushrooms casts flickering shadows on the walls, and you hear strange, distant footsteps \nthat send shivers down your spine."
Hoehle_3_PickUp = "You can pluck a few of the glowing mushrooms; they emit an eerie light that might be of use."
Hoehle_4_Examine = "The rumbling of an unseen source fills the cave with an unsettling sound. The walls appear to respond to the noises."
Hoehle_4_Touch = "As you touch the walls, you feel faint vibrations, as if the cave itself is alive and breathing."
Hoehle_4_Perceive = "The rumbling grows louder, and you can no longer ignore it. It seems to come from the depths of the cave, and you \nfeel surrounded by something ancient."
Hoehle_4_PickUp = "There's nothing nearby to pick up."
Hoehle_5_Examine = "You enter a secret chamber in the cave, surrounded by ancient relics and runes carved into the walls. \nThe room is filled with an eerie presence."
Hoehle_5_Touch = "The relics are cold and evoke a ghostly feeling. Your touch awakens memories of long-forgotten times."
Hoehle_5_Perceive = "The runes emit a faint glow, creating a strange whisper in the chamber. You sense that the relics tell a story, if only \nyou listen closely."
Hoehle_5_PickUp = "Among the ancient relics, you find a mysterious artifact that you can pick up. It feels cold and enigmatic in your \nhands."
Hoehle_6_Examine = "The cave splits into a dark fork at this point, with the darkness seeming even deeper there, and a cold draft \nblows towards you."
Hoehle_6_Touch = "The walls of the fork are permeated with an icy cold. Your touch reveals nothing extraordinary, only the \nsuffocating darkness."
Hoehle_6_Perceive = "In the fork, you hear faint footsteps and echoes of hushed whispers. The darkness appears particularly thick and \nimpenetrable here."
Hoehle_6_PickUp = "There's nothing to pick up here, only the allure of the unknown path."
Hoehle_7_Examine = "The cave is covered by massive stalactites that hang like menacing spears from the ceiling. Dripping water creates a \nsteady, echoing trickle."
Hoehle_7_Touch = "The stalactites are cold and damp, and the water dripping from them leaves a cold shiver on your skin."
Hoehle_7_Perceive = "The sound of water is accompanied by an eerie echo, and you sense that the cave holds more secrets than you can \nimagine."
Hoehle_7_PickUp = "There's nothing to pick up here, except for the drops that incessantly fall from the stalactites."
Hoehle_8_Examine = "In this part of the cave, you feel a sinister presence thickening in the air. Shadows move as if they have a life of \ntheir own."
Hoehle_8_Touch = "The darkness here is so dense that your hand becomes nearly invisible when you hold it up to your face. You feel \nthe presence on your skin."
Hoehle_8_Perceive = "The darkness seems alive here, and you hear eerie whispers in an unknown language that you don't understand."
Hoehle_8_PickUp = "There's nothing to pick up here, only the menacing presence that seems to bear down on you."
Hoehle_9_Examine = "In this part of the cave, the darkness is absolute, and you can't make out any details. It feels like an endless abyss, \nand an unsettling chill runs down your spine."
Hoehle_9_Touch = "As you reach out, your hand encounters only an empty void, and the cold, empty air seems to swallow your touch."
Hoehle_9_Perceive = "The inky blackness is so deep that it feels suffocating. You strain your ears, but all you hear is the echoing silence, \nas if this part of the cave is devoid of life."
Hoehle_9_PickUp = "In this part of the cave, there's nothing to pick up, only an oppressive emptiness that surrounds you."

Sumpf_1 = "You stand at the edge of a gloomy swamp, where sluggish waters are swallowed by an eerie mist."
Sumpf_2 = "The water in the swamp is murky and opaque. The surface is constantly rippled with a low, eerie murmur."
Sumpf_3 = "A rotting tree trunk emerges from the swamp. It's covered with slippery algae and appears unstable."
Sumpf_4 = "The booming calls of cicadas fill the air. Dense reeds surround you, and the ground feels boggy."
Sumpf_5 = "You find yourself in a small clearing in the swamp. Strange, glowing moss grows on the ground."
Sumpf_6 = "As you watch in awe, strange, ethereal lights begin to dance around you. These mystical orbs, resembling tiny \nfairies, swirl in a mesmerizing display. It's as though they are guiding you, fluttering around your body with an \nenchanting grace. Their soft, radiant glow illuminates the path ahead, inviting you to follow their whimsical lead."
Sumpf_7 = "A deep, gurgling sound emanates from the depths of the swamp. It sounds as if something large is moving \ndown there."
Sumpf_8 = "You stand at the edge of a deeper section of the swamp, where the mud appears particularly thick and sticky."
Sumpf_9 = "A narrow, moss-covered path winds through the swamp, shrouded in ghostly tendrils of mist. It leads deeper into \nthe impenetrable forest."
Sumpf_1_Examine = "The gloomy swamp sprawls before you, shrouded in an eerie mist. Moss-covered trees loom in the distance."
Sumpf_1_Touch = "As you dip your hand into the water, it's chilling and feels slimy. The murky depths hide secrets."
Sumpf_1_Perceive = "The distant croaking of frogs fills the air, and the oppressive mist swirls around you, creating an eerie atmosphere."
Sumpf_1_PickUp = "There's nothing nearby to pick up, but the air is heavy with anticipation."
Sumpf_2_Examine = "The swamp's waters are murky and filled with unseen creatures. The surface ripples with strange movements."
Sumpf_2_Touch = "The water is colder than expected, and your hand vanishes into the cloudy depths. It feels like something might be \nlurking below."
Sumpf_2_Perceive = "A cacophony of insect noises echoes around you, and the constant rippling of water is oddly hypnotic."
Sumpf_2_PickUp = "You can't find anything worth picking up in the muddy water."
Sumpf_3_Examine = "A rotting tree trunk rises from the swamp, covered in slimy algae. It looks treacherous to traverse."
Sumpf_3_Touch = "The tree trunk is damp and slippery to the touch. It feels unstable and ready to give way under your weight."
Sumpf_3_Perceive = "The calls of hidden creatures echo from the surrounding reeds, and you sense the presence of life teeming in \nthe muck."
Sumpf_3_PickUp = "There's nothing to pick up on the decaying tree trunk."
Sumpf_4_Examine = "The deafening chorus of cicadas fills the air, making it hard to concentrate. The reeds sway gently in the breeze."
Sumpf_4_Touch = "The reeds are rough and coarse, scratching your skin as you touch them. They seem to whisper secrets in the wind."
Sumpf_4_Perceive = "The symphony of cicadas is almost hypnotic, and you can hear the occasional splash in the water as some creature \nmoves about."
Sumpf_4_PickUp = "There's nothing to pick up among the reeds, but the sounds of the swamp are captivating."
Sumpf_5_Examine = "You stand in a small clearing in the swamp, surrounded by glowing moss. The eerie, radiant plants carpet the \nground."
Sumpf_5_Touch = "The moss is soft and oddly warm to the touch, emitting a faint, ghostly light. It feels strangely comforting."
Sumpf_5_Perceive = "The moss seems to emit a soft hum, and you sense that the clearing has a serene, otherworldly quality."
Sumpf_5_PickUp = "You can gather a handful of the glowing moss, creating a makeshift source of dim light."
Sumpf_6_Examine = "You study the enchanting lights closely, completely unaware of their nefarious intent. Their delicate dance \nonly seems to intensify as they guide you towards an area of the swamp that appears deceptively solid."
Sumpf_6_Touch = "As you reach out to touch one of the lights, it responds by enticing you deeper into the swamp. The soft glow \nbeneath your fingertips hides the trap you're walking into, luring you further into the unknown."
Sumpf_6_Perceive = "Your senses remain inextricably tied to the mischievous lights, leading you into increasingly unstable terrain. \nThe ground grows softer with each step, a treacherous path orchestrated by the lights to further their malevolent \ndesign."
Sumpf_6_PickUp = "Despite your attempts to grasp the lights, they continue their relentless quest to ensnare you in their trap. Every \nmovement you make results in the ground becoming more and more treacherous, as if the very swamp conspires \nwith the lights to lead you into an ominous fate."
Sumpf_7_Examine = "A deep, gurgling sound emanates from the depths of the swamp, where the waters seem impenetrably dark \nand deep."
Sumpf_7_Touch = "The water here is chilling to the touch and feels unnaturally thick. It's as if the swamp itself is breathing."
Sumpf_7_Perceive = "The gurgling intensifies, and you can't shake the feeling that something massive lurks beneath the surface."
Sumpf_7_PickUp = "In the depths of this part of the swamp, you can't find anything to pick up."
Sumpf_8_Examine = "You stand at the edge of a deep, mucky pit in the swamp, and it seems like any misstep could lead to sinking into \nthe mire."
Sumpf_8_Touch = "The mud is sticky and clings to your fingers. It seems bottomless, and a shiver runs down your spine."
Sumpf_8_Perceive = "The pit emanates a nauseating stench, and you can hear the muffled cries of unseen creatures below."
Sumpf_8_PickUp = "In the muck of the pit, there's nothing worth picking up."
Sumpf_9_Examine = "A narrow, moss-covered path winds through the swamp, disappearing into the ghostly tendrils of mist. The path \nseems to lead deeper into the impenetrable forest."
Sumpf_9_Touch = "The moss-covered path is soft beneath your feet, and it feels as if you're walking on a path older than time."
Sumpf_9_Perceive = "The path is shrouded in a strange, mystical mist, and you sense that it holds the secrets of the ancient forest."
Sumpf_9_PickUp = "Along the path, you find a small, intricately carved stone that you can pick up, a relic from times long past."

Kueste_1 = "You stand on a wide, sandy beach, where the gentle waves of the sea lap at the shore."
Kueste_2 = "Tall rocky cliffs rise before you, their rugged surfaces smoothed by the constant waves. In the distance over the \nwater, you can see mysterious lights dancing."
Kueste_3 = "The beach is covered in countless seashells that crunch beneath your every step. The darkness is pierced by \nmysterious lights over the water."
Kueste_4 = "The sea roars, and frothy waves crash upon the shore. Over the water, you can see mysterious lights dancing in the \ndistance."
Kueste_5 = "Rocky tide pools lie before you, filled with a variety of marine life. In the distance, over the water, the mysterious \nlights continue to be visible."
Kueste_6 = "Weathered remnants of a pier protrude from the water, and there are still some timber logs to be seen. \nThe darkness is broken by the mysterious lights over the water."
Kueste_7 = "The shore is lined with lush seagrass meadows that sway gently in the wind."
Kueste_8 = "An old shipwreck rests on the beach, marked by salt and waves. Over the sea, the mysterious lights move like \ndancing spirits."
Kueste_9 = "Before you stand the decayed remains of an ancient monastery that once stood on the edge of the coast. Its Gothic \narches and crumbling walls bear witness to bygone eras. \nIn the distance over the water, you can see mysterious lights dancing."
Kueste_1_Examine = "The wide, sandy beach stretches before you, with seagulls soaring overhead. In the distance, mysterious lights \ndance over the water."
Kueste_1_Touch = "The warm sand feels soft between your toes, and the waves wash over your feet, creating a soothing sensation."
Kueste_1_Perceive = "The sound of crashing waves fills the air, and the salty sea breeze invigorates your senses. Mysterious lights flicker \nin the distance, guiding your curiosity."
Kueste_1_PickUp = "You can't find anything of value to pick up on the beach, but the promise of adventure beckons."
Kueste_2_Examine = "Tall, rugged cliffs rise before you, and you feel small in their imposing presence. Mysterious lights dance over the \ndistant waters."
Kueste_2_Touch = "The rough surface of the cliffs is cool and weathered, revealing the timeless nature of these ancient formations."
Kueste_2_Perceive = "The crashing waves echo off the cliffs, creating a mesmerizing cacophony. The mysterious lights over the water \nadd an aura of mystique."
Kueste_2_PickUp = "There's nothing to pick up amidst the rocky cliffs, but the allure of exploration calls."
Kueste_3_Examine = "Countless seashells cover the beach, glistening in the moonlight. The distant waters are illuminated by the \nenigmatic lights."
Kueste_3_Touch = "The seashells feel delicate and varied under your fingers, and they crunch as you walk. The cool breeze carries \nthe scent of the sea."
Kueste_3_Perceive = "The sound of waves lapping at the shore mingles with the distant, ethereal lights. A sense of wonder washes \nover you."
Kueste_3_PickUp = "You can collect some of the seashells, their beauty and history evident in your hands."
Kueste_4_Examine = "The sea roars with whitecaps, and the foamy waves crash dramatically on the shore. Mysterious lights continue \ntheir dance over the water."
Kueste_4_Touch = "The waves rush to embrace your feet, their cool spray invigorating. The power of the ocean is awe-inspiring."
Kueste_4_Perceive = "The rhythmic, thunderous sound of the surf is both calming and powerful. The mysterious lights over the water add \nan air of enchantment."
Kueste_4_PickUp = "Amidst the turbulent surf, you find nothing worth picking up, but the energy of the sea calls to your spirit."
Kueste_5_Examine = "Rocky tide pools are filled with a multitude of marine life, revealing a hidden world of creatures. Over the water, \nthe mysterious lights persist in their dance."
Kueste_5_Touch = "The tide pools are cool to the touch, and your fingers encounter an array of textures and sensations, from slippery \nseaweed to smooth stones."
Kueste_5_Perceive = "The life within the tide pools is bustling, and you hear the gentle calls of the hidden inhabitants. Mysterious lights \nover the water lend a sense of enchantment to the scene."
Kueste_5_PickUp = "In the tide pools, you can pick up a small, colorful seashell as a keepsake of this vibrant ecosystem."
Kueste_6_Examine = "The remnants of an old pier reach out from the water, bearing the scars of time and nature's fury. \nMysterious lights cast an otherworldly glow over the water."
Kueste_6_Touch = "The weathered wood of the pier ruins is smooth in some places, rough in others, and it carries the stories of \ncountless tides."
Kueste_6_Perceive = "The sounds of creaking wood and the distant waves surround you, accompanied by the ethereal lights that seem to \nbeckon you onward."
Kueste_6_PickUp = "Among the remnants of the pier, you discover an ancient coin that you can pick up as a piece of forgotten history."
Kueste_7_Examine = "The shoreline is adorned with lush seagrass meadows that sway gently in the sea breeze. The moonlight reveals the \nmysterious lights dancing above the water."
Kueste_7_Touch = "The seagrass is soft to the touch, its tendrils tickling your fingers as you run your hand over the meadows. The salty \nair carries the scent of the sea."
Kueste_7_Perceive = "The gentle rustling of seagrass in the wind is almost hypnotic. The mysterious lights over the water add an \nenchanting quality to the scene."
Kueste_7_PickUp = "You can collect a small bundle of seagrass, feeling a connection to the coastal beauty."
Kueste_8_Examine = "An old shipwreck rests on the beach, marked by salt and waves. Mysterious lights dance over the sea, casting an \neerie glow on the scene."
Kueste_8_Touch = "The shipwreck's wood is weathered and rough to the touch. It seems to carry the weight of history and countless \nvoyages."
Kueste_8_Perceive = "The eerie creaking of the shipwreck, combined with the distant lights, creates an otherworldly atmosphere."
Kueste_8_PickUp = "Amidst the shipwreck, you find a weathered, but intriguing, message in a bottle that you can pick up as a relic \nof the sea."
Kueste_9_Examine = "Before you stand the decayed remains of an ancient monastery that once stood on the edge of the coast. Its Gothic \narches and crumbling walls bear witness to bygone eras. \nIn the distance over the water, you can see mysterious lights dancing."
Kueste_9_Touch = "The aged stone is cool to the touch, and you can feel the weight of history in the monastery's ruins."
Kueste_9_Perceive = "The sound of the wind through the empty arches creates an eerie resonance. \nThe distant, mysterious lights over the water add an aura of mystique."
Kueste_9_PickUp = "There's nothing to pick up among the monastery ruins, but the allure of exploration calls."

Ebene_1 = "You find yourself in the midst of a vast grassland, where thick fog shrouds the landscape. The air is heavy with \nmoisture, and you can barely see beyond a few feet."
Ebene_2 = "Gentle breezes rustle the tall grass around you, their whispers barely audible in the dense fog. Visibility is limited, \nand the world beyond remains veiled."
Ebene_3 = " In this eerie stillness, you perceive slight movements around you. These subtle motions are almost silent, with only \nthe gentle rustling of grass breaking the silence. It's as if something is moving around you, concealed by the \nthick mist."
Ebene_4 = "A small, open meadow appears before you, devoid of tall grass. The silence here is eerie, the dense fog muffling \neven the sound of your own footsteps."
Ebene_5 = "A solitary tree stands in the foggy plain, its branches barely visible. The tree exudes an eerie, lonesome presence, \nand the fog makes it seem like a spectral guardian."
Ebene_6 = "You hear the gentle murmur of a stream somewhere nearby, but the fog makes it nearly impossible to locate. \nThe sound is a faint, distant comfort in this ethereal landscape."
Ebene_7 = "In the midst of the mist, something peculiar happens. The fog seems to take on an elusive form, simultaneously \ndiscernible and intangible. An overwhelming dread washes over you as you struggle to comprehend this eerie \nphenomenon, a sensation of unsettling fear gnawing at your core."
Ebene_8 = "You stumble upon a circle of ancient standing stones, their origins lost in the fog. They exude an aura of \ntimelessness, their purpose a mystery."
Ebene_9 = "As you move deeper into the foggy grassland, you sense that something may be hidden here. The fog seems to \nconceal secrets, making the atmosphere even more enigmatic."
Ebene_1_Examine = "The thick fog envelops the grassland, shrouding everything in a ghostly haze. You can barely see beyond a few feet, \nand the atmosphere is eerie."
Ebene_1_Touch = "The tall grass is damp with dew, and your fingers become moist as you brush through it. The fog clings to your skin, \ncreating a sense of otherworldly moisture."
Ebene_1_Perceive = "Your senses are overwhelmed by the dense fog. Every sound, every movement seems muffled and distant. \nThe world feels ethereal and veiled."
Ebene_1_PickUp = "The grassland offers nothing to pick up, only the palpable mystery of the fog that obscures your surroundings."
Ebene_2_Examine = "Gentle breezes sway the tall grass, their whispers barely audible in the dense fog. The plain stretches as far as you \ncan see, lost in the mist."
Ebene_2_Touch = "The grass feels soft and cool to the touch, and the fog-kissed blades rustle beneath your hand. It's a soothing \nsensation amidst the eerie stillness."
Ebene_2_Perceive = "You hear the faint, soothing whispers of the breeze through the grass. The fog conceals the horizon, leaving you \nwith a sense of isolation and serenity."
Ebene_2_PickUp = "You find nothing worth picking up in this tranquil meadow, only the soft embrace of the fog."
Ebene_3_Examine = "You catch a glimpse of something lurking nearby. There's a sense of an elusive presence, and it's as though the \nhidden observer is keenly watching your every move."
Ebene_3_Touch = "You reach out, your hand brushing against the cool, damp grass. Your touch feels a bit unnerving as if the environment is aware of your presence. The sensation leaves you with the uncanny feeling of being closely watched."
Ebene_3_Perceive = "You hone your senses to detect anything unusual in the almost suffocating mist. A faint movement, barely audible, \nstirs the fog. It's as though something is silently pacing around you, perhaps curious or cautious."
Ebene_3_PickUp = "As you consider picking up something from the ground, you notice that the grass beneath your feet is somewhat \ndisturbed, hinting at a recent presence. It's like you're treading through the territory of an unseen observer."
Ebene_4_Examine = "The small meadow stands in stark contrast to the surrounding tall grass. The fog lends an eerie stillness to the open \nspace, and your own footsteps are muffled."
Ebene_4_Touch = "The meadow is cool and calm, a sanctuary amidst the foggy landscape. The silence is almost reverential, as if nature \nitself holds its breath."
Ebene_4_Perceive = "The silence in the meadow is profound. Even the fog seems to hush, and you sense a subtle, mystical presence \nin this quiet haven."
Ebene_4_PickUp = "In the silent meadow, there's nothing to pick up, but the atmosphere itself is a treasure."
Ebene_5_Examine = "The lone tree stands as a sentinel in the fog, its branches barely visible. It feels like a relic of another time, \na guardian in this ethereal realm."
Ebene_5_Touch = "The tree's rough bark is barely discernible in the fog. It exudes an eerie, ancient energy, as if it holds secrets within \nits gnarled branches."
Ebene_5_Perceive = "The tree feels like a living presence, its solitary nature accentuated by the fog. You can't help but feel a \nconnection to this sentinel in the mist."
Ebene_5_PickUp = "Around the tree, there's nothing to pick up, but its enigmatic aura holds your attention."
Ebene_6_Examine = "The gentle murmur of a stream reaches your ears, though the fog makes it difficult to pinpoint its source. \nIt's as if the stream is a phantom in this misty world."
Ebene_6_Touch = "The sound of running water is tantalizingly close, but the fog conceals the stream from your touch. \nThe moisture in the air adds to the sensory puzzle."
Ebene_6_Perceive = "The stream's murmur provides a faint sense of direction, but the fog still obscures its location. \nThe ambiance is both eerie and intriguing."
Ebene_6_PickUp = "You can't pick up the stream, but the thought of finding and following its course intrigues you."
Ebene_7_Examine = "As you intently examine the enigmatic form within the mist, you notice subtle, ever-changing contours, \nlike a specter in flux. It's both there and not there, defying easy description."
Ebene_7_Touch = "Hesitatingly, you extend your hand, but it meets no resistance, just a cool, damp feeling where the form should be. \nYour unease deepens."
Ebene_7_Perceive = "Attempting to perceive its true nature, you find yourself locked in a disconcerting dance of perception. \nWhat is tangible and what is illusory? The dread lingers."
Ebene_7_PickUp = "Despite your instincts urging caution, you reach out to grasp the elusive form, but your hands grasp empty air. \nYour sense of fear intensifies, like the ominous presence knows you better than you know yourself."
Ebene_8_Examine = "A circle of ancient standing stones looms in the fog, their origins lost to the mist. They emanate an aura of \ntimelessness, and the fog adds an element of mystique to their presence."
Ebene_8_Touch = "The rough surfaces of the stones hint at centuries of history. You can feel the ancient energy they hold, as if they \nguard secrets of the ages."
Ebene_8_Perceive = "The standing stones are both a mystery and a source of fascination. The fog cloaks them in an enigmatic shroud, \nmaking them seem like forgotten sentinels."
Ebene_8_PickUp = "Around the standing stones, you find nothing to pick up, but the air is heavy with the weight of history."
Ebene_9_Examine = "As you move deeper into the foggy grassland, a sense of hidden potential fills the air. The fog conceals something, \nand the atmosphere is rife with enigma."
Ebene_9_Touch = "The fog becomes denser as you proceed, and your sense of touch is heightened by the anticipation of discovery. \nIt's as if the fog itself has secrets to unveil."
Ebene_9_Perceive = "Each step is an exploration into the unknown. The fog teases your senses, and you can't help but feel that \nsomething remarkable lies concealed in this misty realm."
Ebene_9_PickUp = "The grassland offers nothing tangible to pick up, but the promise of hidden treasure keeps your curiosity burning."

Veridia_1 = "In the misty marketplace, a woman with flowing brown hair and a yellow dress tends to her open-air stall, offering \na variety of wares, her presence casting a gentle warmth on the otherwise quiet square."
Veridia_2 = "An old market stall stands empty, its faded awning sagging under the weight of time. Silhouettes can be seen in the \nbackground, moving quietly through the mist."
Veridia_3 = "A weathered man, dressed in the attire of a fisherman, stands near his collection of fishing gear. He appears deeply \nconcerned, his eyes focused on something unseen in the mist. \nThe air is heavy with anticipation, and silhouettes occasionally pass by, shrouded in mystery."
Veridia_4 = "You tread along a cobblestone path in Veridia, which seems to lead directly to the marketplace. At the center of \nthe square stands an old stone fountain. Amidst the lingering mist, elusive silhouettes move, adding an enigmatic \ntouch to the deserted village."
Veridia_5 = "A young girl, around the age of 10, inspects the village well with great curiosity. Her efforts suggest that she's \nsearching for something, yet she appears to have found no success."
Veridia_6 = "A quaint fountain stands in the square, its waters still and unmoving. Silhouettes occasionally gather around the \nfountain, perhaps seeking respite from the mist."
Veridia_7 = "You find yourself in a small square surrounded by crumbling buildings. Nature has begun reclaiming the space, \nwith vines and foliage covering much of the architecture. A feeling of timelessness and abandonment fills the air."
Veridia_8 = "An old statue, now weathered and partially overgrown, stands as a silent guardian of the marketplace. Silhouettes \npay their respects, their actions and intentions hidden in the mist."
Veridia_9 = "As you venture deeper into the misty marketplace, you come across a self-assured middle-aged man with a white \nshirt and a brown vest. \nHe stands by a stall selling various artifacts that are unfamiliar to you."
Veridia_1_Examine = "The marketplace stands eerily quiet, shrouded in a light mist that lends an air of abandonment. Faint silhouettes move in the distance, carrying the secrets of the village."
Veridia_1_Touch = "The cobblestones underfoot feel cool and slightly damp, as if they hold the memories of countless footsteps. The mist clings to your skin, making every touch an ethereal experience."
Veridia_1_Perceive = "The silence in the marketplace is profound, save for the soft whispers of the mist. The silhouettes move quietly, \nleaving you to wonder about the lives hidden in the fog."
Veridia_1_PickUp = "In this deserted square, you find nothing worth picking up, but the enigmatic silhouettes beckon you to explore."
Veridia_2_Examine = "An old market stall stands as a relic of busier days, its emptiness telling tales of a past long gone. Silhouettes can be \nseen in the background, their purpose veiled in mystery."
Veridia_2_Touch = "The wooden frame of the abandoned stall feels weathered and slightly rough under your hand. The presence of \nsilhouettes nearby adds to the intrigue of this forgotten space."
Veridia_2_Perceive = "The empty stall evokes a sense of nostalgia, and the silhouettes moving in the mist suggest that life still lingers, if \nhidden. Their actions remain a puzzle, waiting to be solved."
Veridia_2_PickUp = "Around the stall, there's nothing worth picking up, but the sight of the silhouettes offers a glimpse into the village's \nenigmatic present."
Veridia_3_Examine = "A gentle breeze stirs the mist, whispering secrets that hang in the air. Silhouettes move in the distance, like specters, making the village feel alive in its quiet solitude."
Veridia_3_Touch = "The breeze caresses your skin, its touch cool and soothing. It carries the essence of the village, while the silhouettes create an ethereal ballet of movement in the fog."
Veridia_3_Perceive = "The whispering breeze seems to narrate the stories of the village. Silhouettes drift through the marketplace, their \nintentions and identities hidden by the mist."
Veridia_3_PickUp = "Amidst the breeze and mist, there's nothing tangible to pick up, but the presence of the silhouettes beckons you to explore."
Veridia_4_Examine = "As you inspect the cobblestone path, you notice how meticulously crafted it is, despite the surrounding desolation. \nThe silhouettes in the mist seem to move with purpose, perhaps drawing you closer to unravel their secrets."
Veridia_4_Touch = "Running your fingers across the cool, ancient cobblestones, you feel a connection to the village's history. \nThe silhouettes in the distance remain as enigmatic as ever, prompting curiosity."
Veridia_4_Perceive = "The mist amplifies the eerie silence that hangs over the marketplace. You can't help but feel like an outsider in a \nvillage where the silhouettes carry the untold tales of what has transpired."
Veridia_4_PickUp = "Despite the captivating atmosphere, there's nothing tangible to pick up on the path. However, the presence of the \nsilhouettes beckons you to explore the mysteries concealed within Veridia."
Veridia_5_Examine = "Mysterious figures move about the marketplace, their purpose shrouded in the mist. Silhouettes are the village's hidden residents, contributing to the sense of intrigue and abandonment."
Veridia_5_Touch = "The silhouettes are just beyond your reach, their presence lending an air of mystique to the misty square. You can't help but wonder about their stories and intentions."
Veridia_5_Perceive = "The girl seems to be inspecting the well. The mist amplifies the sense of isolation and enigma."
Veridia_5_PickUp = "Amidst the enigmatic figures, you find nothing worth picking up, but the village's secrets appear to be carried by these spectral residents."
Veridia_6_Examine = "A quaint fountain stands still in the square, its waters untouched. Silhouettes gather around it, perhaps seeking \nsolace or a moment of reflection amidst the mist."
Veridia_6_Touch = "The water in the fountain feels cool and inviting, yet untouched. Silhouettes occasionally approach it, adding a \nsense of serenity to the atmosphere."
Veridia_6_Perceive = "The silent fountain serves as a quiet refuge for the silhouettes. Their actions, however, are concealed, and the mist \ngrants them an air of quiet contemplation."
Veridia_6_PickUp = "Around the fountain, there's nothing to pick up, but the presence of the silhouettes adds a layer of enigmatic \nbeauty to this tranquil scene."
Veridia_7_Examine = "As you examine the overgrown square, you marvel at the tenacity of nature reclaiming what was once a bustling \nspace. The architecture, though in ruins, carries an air of history and mystery. You wonder what \nstories these forgotten walls could tell."
Veridia_7_Touch = "The vines and foliage covering the square feel damp and cool to the touch. You're reminded of how nature has a \nway of healing even the deepest wounds. The silence is only broken by the sound of rustling leaves in the breeze."
Veridia_7_Perceive = "The square is cloaked in an almost reverential silence. You can't help but feel a connection to the past, a sense of \ntimelessness, as if the square exists in a different era. The gentle rustling of the leaves adds to the serenity of \nthe place."
Veridia_7_PickUp = "You find nothing to pick up in this overgrown square. However, the entwined beauty of nature and ruins, along \nwith the sense of time standing still, keeps you intrigued about the history of this place."
Veridia_8_Examine = "An old statue stands as a silent guardian, its features eroded by time and the elements. Silhouettes pay their \nrespects, their actions and intentions hidden in the mist."
Veridia_8_Touch = "The stone of the statue feels cool and slightly rough under your touch. Silhouettes occasionally gather around it, \nadding an element of reverence to the enigmatic atmosphere."
Veridia_8_Perceive = "The statue holds a place of significance, and the silhouettes' actions suggest a deep connection to the village's \nhistory. Their stories remain concealed by the mist."
Veridia_8_PickUp = "Around the statue, there's nothing to pick up, but the silhouettes' actions provide a sense of reverence and add to \nthe sense of mystery."
Veridia_9_Examine = "As you move deeper into the misty marketplace, the village's secrets seem to thicken. Silhouettes are numerous, their movements and intentions hidden by the fog."
Veridia_9_Touch = "The mist becomes denser, and your sense of touch is heightened by the anticipation of discovery. The presence of countless silhouettes adds to the allure of the veiled mystery."
Veridia_9_Perceive = "Each step takes you further into the enigma. The silhouettes navigate the fog with familiarity, and you can't help \nbut feel that the village holds untold stories waiting to be unveiled."
Veridia_9_PickUp = "In this thickening mist, there's nothing tangible to pick up, but the promise of veiled mysteries keeps your curiosity alive."

ZVeridia_1 = "You stand in the village marketplace, which now lies in ruins. The once-charming scene is marred by destruction, \nwith shattered stalls and buildings. Amidst the wreckage, you see faint silhouettes of survivors searching for hope."
ZVeridia_2 = "The remnants of a market stall stand like a ghostly reminder of what was. Silhouettes move in the background, \nscavenging what little remains in the mist-covered aftermath."
ZVeridia_3 = "A heavy silence blankets the shattered marketplace. Broken structures and debris are scattered everywhere. \nOccasional silhouettes move about, their actions a testament to their resilience in the face of disaster."
ZVeridia_4 = "The stone well is now a shattered relic, a symbol of the village's demise. Silhouettes gather around, perhaps \nsearching for any sign of life or remnants of their past."
ZVeridia_5 = "Amid the wreckage, resilient figures move with determination. Their silhouettes tell a story of survival and \nhope, as they work together to rebuild what was lost."
ZVeridia_6 = "The quaint fountain lies in pieces, its waters gone. Silhouettes occasionally gather, sharing stories of \ncourage and determination amidst the chaos."
ZVeridia_7 = "The cobblestone path is marred with destruction, leading further into the village. Silhouettes move with a sense \nof purpose, navigating through the wreckage, driven by the desire to rebuild."
ZVeridia_8 = "The old statue stands resilient, albeit chipped and worn. Silhouettes pay their respects, finding strength in \nthe symbol of endurance, even in the face of devastation."
ZVeridia_9 = "As you venture deeper into the ruined village, the mist grows thicker. Silhouettes are more numerous, and \ntheir actions speak of determination and unity. The village, though devastated, is far from defeated."
ZVeridia_1_Examine = "The once-thriving marketplace now lies in ruins. Broken stalls and buildings stretch out before you.\nFaint silhouettes of survivors can be seen, searching for any sign of hope amidst the devastation."
ZVeridia_1_Touch = "The debris underfoot feels cold and unforgiving. Your hand brushes against shattered wood and broken \nstone, a tactile reminder of the village's tragic fate."
ZVeridia_1_Perceive = "A heavy silence hangs in the misty air, occasionally broken by muffled sobs and determined whispers. \nThe silhouettes move with a sense of purpose, driven by the collective will to rebuild."
ZVeridia_1_PickUp = "Amidst the wreckage, there's nothing to be picked up, only a poignant reminder of the village's resilience."
ZVeridia_2_Examine = "The remnants of a market stall stand as a ghostly shell of the past. In the background, silhouettes \nmove with somber determination, scavenging the remains of what once thrived here."
ZVeridia_2_Touch = "The broken wooden frame of the stall feels rough and splintered under your touch. The silhouettes \nappear to work together, seeking solace in unity amid the ruins."
ZVeridia_2_Perceive = "The empty stall is now a symbol of the village's indomitable spirit. Silhouettes gather in the mist, \nshowing strength and resolve in the face of loss."
ZVeridia_2_PickUp = "Around the stall, there's nothing left to be picked up. However, the silhouettes working in the \nbackdrop paint a picture of hope amidst adversity."
ZVeridia_3_Examine = "A profound silence envelops the shattered marketplace, with debris and remnants of a once-thriving \nvillage scattered in disarray. Silhouettes navigate this somber landscape, displaying the courage to carry on."
ZVeridia_3_Touch = "The heavy silence is a palpable presence in the mist, and you can feel the weight of the village's \ntragedy in every step. The silhouettes represent the determination to rebuild, even in the absence of words."
ZVeridia_3_Perceive = "Amidst the stillness, whispers of determination and survival can be heard. Silhouettes move, a \nliving testament to the indomitable spirit that refuses to yield to despair."
ZVeridia_3_PickUp = "In the eerie silence, there's nothing that can be picked up. The presence of silhouettes is a reminder \nthat the village's story is far from over."
ZVeridia_4_Examine = "The once-vital well is now shattered and dry, a symbol of the village's suffering. Silhouettes gather \naround it, perhaps searching for remnants of the life and community they once knew."
ZVeridia_4_Touch = "The fragmented well feels like a monument to the village's misfortune. Silhouettes surround it, their \npresence a reflection of a collective strength to face adversity."
ZVeridia_4_Perceive = "The silhouettes at the well seem to draw strength from the broken symbol of life. Their shared \nmoments of reflection and resilience are a testament to the human spirit's ability to endure."
ZVeridia_4_PickUp = "Around the shattered well, you find nothing to pick up, but the silhouettes give meaning to this solemn \ngathering place."
ZVeridia_5_Examine = "In the midst of destruction, figures move with unwavering determination. Silhouettes come together, their \nactions illustrating the spirit of survival and hope amid the chaos."
ZVeridia_5_Touch = "The silhouettes are just beyond reach, a symbol of the enduring strength that drives the survivors forward. \nTheir unity is a testament to the village's resilience."
ZVeridia_5_Perceive = "The survivors work together with determination and resilience, their silhouettes dancing in the mist. \nTheir collective effort is a beacon of hope amidst the ruin."
ZVeridia_5_PickUp = "Amidst the resilient figures, there is nothing to be picked up, but their actions inspire a sense of unity \nand purpose, even in the face of disaster."
ZVeridia_6_Examine = "The once-charming fountain now lies in shattered disarray, its waters gone. Silhouettes occasionally gather \naround it, sharing stories of courage and determination amidst the chaos."
ZVeridia_6_Touch = "The remnants of the fountain feel cool and inviting, yet irreparably damaged. Silhouettes create an atmosphere \nof resilience and the shared struggle to rebuild."
ZVeridia_6_Perceive = "In the ruins of the fountain, silhouettes find solace, their movements reflecting a sense of shared strength \nand unwavering resolve."
ZVeridia_6_PickUp = "Around the broken fountain, there's nothing to be picked up. Yet the silhouettes convey a spirit of \ncamaraderie and tenacity, even in the face of destruction."
ZVeridia_7_Examine = "The cobblestone path, once a guide through the village, is now marred by destruction. Silhouettes move along \nthe path with a clear sense of purpose, navigating through the wreckage."
ZVeridia_7_Touch = "The cobblestones underfoot remain steadfast amidst the chaos, offering a reliable path forward. Silhouettes in \nthe distance move with determination, as if leading the way to rebuilding."
ZVeridia_7_Perceive = "The path leads deeper into the village, and the silhouettes suggest that there's more to discover. \nTheir collective movement indicates a shared journey of uncovering hidden stories and mysteries."
ZVeridia_7_PickUp = "On the cobblestone path, you find nothing to pick up, but the silhouettes beckon you to follow, as if they know \nthe way to the village's secrets."
ZVeridia_8_Examine = "The old statue stands resilient, albeit chipped and worn. Silhouettes pay their respects, finding strength in \nthe symbol of endurance, even in the face of devastation."
ZVeridia_8_Touch = "The stone of the statue feels cool and slightly rough under your touch. Silhouettes occasionally gather around it, \nadding an element of reverence to the enigmatic atmosphere."
ZVeridia_8_Perceive = "The statue holds a place of significance, and the silhouettes' actions suggest a deep connection to the village's history. \nTheir stories remain concealed by the mist."
ZVeridia_8_PickUp = "Around the statue, there's nothing to pick up, but the silhouettes' actions provide a sense of reverence and add to \nthe sense of mystery."
ZVeridia_9_Examine = "As you venture deeper into the ruined village, the mist grows thicker. Silhouettes are more numerous, and their \nactions speak of determination and unity. The village, though devastated, is far from defeated."
ZVeridia_9_Touch = "The mist becomes denser, and your sense of touch is heightened by the anticipation of discovery. The presence of \ncountless silhouettes adds to the allure of the veiled mystery."
ZVeridia_9_Perceive = "Each step takes you further into the enigma. The silhouettes navigate the fog with familiarity, and you can't \nhelp but feel that the village holds untold stories waiting to be unveiled."
ZVeridia_9_PickUp = "In the shrouded determination of this place, you find nothing to pick up, but the presence of the silhouettes adds \ndepth to the village's resilience and determination."

Vorluna_Dialog = "In the pitch-black cave, a spider-like monster lurks. Its fangs gleam in the darkness, eager to seize the thoughts\nand senses of intruders. A creeping terror settles over the visitors, as if their souls are gripped by invisible\nclaws. Senses stagger, and thoughts twist into a grotesque play. The spider creature weaves a web of madness\nand despair, while it lurks in the shadows, ready to drag its victims into the gaping abyss of madness."
Malikar_Dialog = "A formidable figure cloaked in foreboding armor, accentuating his towering presence. Her very essence exudes an\nominous aura, foretelling of impending doom. He manifests in a colossal, sinister form, exuding an insurmountable,\nmalevolent presence - an unmistakable epitome of malevolence and dread."
Varoth_Dialog = "As the mist closes in around you, it begins to coalesce into a more tangible form, taking on the shape of a \nmonstrous beast. Its bodily contours blur as it takes silent steps. From its shadowy, razor-sharp blades emanate \nmournful sounds that make the heart tremble. Luminous red eyes pierce through the darkness, fiery and eerie. \nIts breath creates the fog, dense and opaque, enveloping everything around. It's a terrifying presence that instills \ndeep fear."
Zyrelia_Dialog = "A ghostly apparition, barely tangible, roams through the twilight. Its whispering essence touches the souls of\npeople, influencing thoughts and emotions. In the stillness of the night, a shrill scream pierces the air, an\necho of past torment. Its gaze from empty eyes carries the weight of long-forgotten secrets, a testament to forgotten\nsufferings. This ghostly presence, trapped between worlds, hovers as a warning of the unknown, a call from beyond."
Malkor_Dialog = "A swamp monster, cloaked in deceptive calm, lurks hidden in the marsh. Its skin resembles decaying moss, soaked\nin a demonic aura. With greedy eyes, it scans for prey that comes near. Its slimy tentacles shoot out, sucking\nin life force and strength. A frigid breath envelops its victims as they grow weaker and more feeble. The howl of\nthe swamp monster echoes through the gloomy swamp, a warning sign of the danger lurking there."
Dreznar_Dialog = "A dark sea monster rises from the depths, its tentacles like shadowy claws, Glowing eyes, radiant with ominous\ncold, pierce through the darkness. A single strike summons storms that devour sky and sea, The balance of the\nelements shatters, nature bows to its will. This demonic creature, a nightmare from ancient legends, spreads fear\nand terror, In the hearts of those who must endure its sinister gaze."
Gegner_Ebene_Dialog = "The heavy mist conceals the wild beast's approach until it bursts forth, lunging at you with a snarl. Its fangs bared, \nit attacks with a sudden ferocity, its eyes gleaming with an untamed hunger. "
Gegner_Hoehle_Dialog = "An undead caster attacks you"
Gegner_Kueste_Dialog = "A seamonster attacks you"
Gegner_Morast_Dialog = "Suddenly, a skeletal hand emerges from the thick, murky swamp water, reaching out menacingly towards you. \nClinging to the rotting remains of a once-proud armor, the hand reveals itself to be a part of a decaying corpse. \nThe foul-smelling muck of the swamp water drips from its bony fingers. As the undead warrior rises from the \ndepths of the swamp, its hollow eye sockets lock onto you, and it lurches forward, ready to attack."
Gegner_Wald_Dialog = "In a sudden, heart-pounding moment, you find yourself under attack. A wildling, perched atop a massive wolf, \nlunges out of the shadows. The wolf's snarling jaws and the wildling's fierce, unrelenting gaze leave you with no \nchoice but to defend yourself."

countertext=["The enemy delivers a critical strike, yet you counter with a powerful blow, leaving him stunned.",
"While the enemy lands a critical hit, you retaliate with a devastating strike, catching him off guard.",
"The enemy's attack hits hard, but your counterattack is even more fierce, surprising him.",
"As the enemy strikes critically, you respond with a fierce counter, throwing him off balance.",
"The enemy's hit is severe, but your counter is swift and powerful, momentarily stunning him.",
"Despite the enemy's critical hit, your counter is relentless, taking him by surprise.",
"The enemy's blow is harsh, but your counterattack is swift and forceful, staggering him.",
"While the enemy scores a critical hit, you launch a fierce counterattack, leaving him dazed.",
"The enemy's strike is brutal, yet your counter is swift and mighty, momentarily stunning him.",
"Despite the enemy's critical hit, your counterattack is fierce, catching him off guard.",
"The enemy lands a critical hit on you, but you counter with a devastating strike that leaves him staggered."]

attacktext=["You strike the enemy, landing a solid hit. In retaliation, he delivers a swift counterattack.",
"Your attack connects with the enemy, dealing a significant blow. He responds with a quick counterstrike.",
"You launch a powerful attack, hitting the enemy with force. He swiftly counterattacks in response.",
"The enemy takes a hit from your attack, staggering back. He retaliates with a swift counterblow.",
"Your strike lands on the enemy, causing him to recoil. In return, he counters with a rapid strike.",
"The enemy is struck by your attack, momentarily off balance. He swiftly retaliates in response.",
"You deliver a strong blow, hitting the enemy with impact. He counters swiftly and decisively.",
"The enemy is hit by your attack, momentarily stunned. He retaliates with a quick counterstrike.",
"Your powerful strike connects with the enemy, pushing him back. He swiftly counters your attack.",
"You land a significant blow on the enemy. In response, he quickly delivers a counterstrike."]

Outro_1 = "The malevolent warlock has been vanquished and falls wordlessly to the ground. His body once again dissolves \ninto five souls, but this time, they slowly dissipate into thin air until they vanish completely into nothingness."
Outro_2 = "Gradually, peace returns to Veridia. The villagers gather around you, praising your bravery and hailing you as their \nhero. The nightmare is over, and the land begins to heal thanks to your valor."
Outro_3 = "Brigitte: \nOh, I can't believe it! You did it! I'm so excited! That was incredible! What just happened was... wow!"
Outro_4 = "Miriam: \nIt seems like those lights weren't nice at all! Thank you so much for helping us. We couldn't have done it \nwithout you!"
Outro_5 = "Ulrich: \nMany years ago, there was a legend of an ancient warlock who ruled these lands. It was said that he was defeated \nin his time. But I always thought it was just a fairy tale."
Outro_6 = "Gottfried: \nIt seems the warlock divided his power into five fragments. As they gained more and more power, they began to \nterrorize the land. Those lights were their way of seeking new victims."
Outro_7 = "Gottfried: \nBe that as it may, I thank you, and I wish you all the best for your future endeavors."
Outro_8 = "Brigitte: \nThank you, kind adventurer. You saved our village from an unspeakable fate."
Outro_9 = "Miriam: \nThank you very much!"
Outro_10 = "Ulrich: \nAye, we owe you a debt of gratitude for putting an end to that wicked curse."
Outro_11 = "As the sun rises slowly, a new day dawns. The oppressive atmosphere gradually lifts from the land, and you set out \nin search of new adventures."
Outro_12 = "The weight of the recent events still lingers, and Veridia's residents will forever remember your heroic feats."
Outro_13 = "You can't help but wonder what challenges and wonders the future holds for you on this intriguing journey."
Outro_14 = "The End"






