#Erster Besuch in Veridia
Einleitung = "You are an adventurer who has wandered into this area for the first time. Upon entering the village, \n you immediately notice that something is very wrong. The atmosphere is dark and oppressive.\n In the town square, you see four people who all seem quite tense..."
Veridia_1 = "You stand before Veridia's marketplace, a gloomy place deep within a dark forest. \n Four individuals are in front of you: a weathered fisherman, a hurried merchant sorting dusty wares, \n an elegant but troubled jewelry vendor, and a silent child by the well, their gaze locked onto the murky water. \n The atmosphere feels oppressive, and all four of them appear tense, as if sensing something ominous."
Veridia_2 = "There is nothing to touch except for the dirt below your feet."
Veridia_3 = "The town is eerily silent, with barely any movement in the streets. The windows of the buildings remain dark, \n and there are no signs of life or activity. The unsettling stillness hangs heavily in the air, \n as if the town itself is holding its breath, waiting for something to happen."
Veridia_4 = "There is nothing to pick up."
Veridia_5 = "Vor dir steht eine junge Frau."
Veridia_6 = "a"
Veridia_7 = "b"
Veridia_8 = "c"
Veridia_9 = "d"
Veridia_10 = "e"
Veridia_11 = "f"
Veridia_12 = "g"
Veridia_13 = "h"
Veridia_14 = "i"
Veridia_15 = "j"
Veridia_16 = "k"
Veridia_17 = "l"
Veridia_18 = "m"
Veridia_19 = "n"
Veridia_20 = "o"


Brigitte_1 = "Before you stands a middle-aged woman with a warm and welcoming demeanor. She exudes an aura of \nwisdom and kindness, wearing modest, earth-toned clothing. Her eyes sparkle with genuine care, and her presence \nin this unsettling atmosphere offers a glimmer of comfort and hope. \nHowever, something appears to weigh heavily on her, evident in the subtle lines of concern etched on her face."
Ulrich_1 = "Before you stands a rugged figure, a fisherman by the looks of him. His clothing is worn and salt-stained, evidence \nof years spent battling the elements. His face, etched with lines from countless days at sea, is weather-beaten \nand stern. He regards you with a mix of curiosity and wariness, his eyes reflecting the uncertainty that \nlooms over the village."
Gottfried_1 = "The man before you appears to be in his middle years, with a sturdy build and attire that speaks of practicality and \nresilience. His clean hair and calm demeanor suggest a life shaped by both challenges and wisdom."
Miriam_1 = "You notice a young girl standing by the fountain, her expression a mix of concern and curiosity. She seems deeply \nabsorbed in studying the old well, her eyes fixed on its moss-covered stones. Her brows are slightly furrowed, \nand she occasionally tilts her head as if trying to decipher some hidden message in the well's worn surface."
